create table Comment (id bigint not null, createdAt datetime, text varchar(2000) not null, story_id bigint, primary key (id))
create table Profile (id bigint not null, email varchar(255) not null, fullname varchar(255) not null, password varchar(20) not null, username varchar(30) not null, primary key (id))
create table Story (id bigint not null, description varchar(4000) not null, dislikes bigint not null, likes bigint not null, mediaUrl varchar(255), type varchar(255), score bigint not null, submittedAt datetime not null, title varchar(255) not null, url varchar(255) not null, version integer not null, primary key (id))
create table Tags (Story_id bigint not null, tags varchar(255))
alter table Profile add constraint UK_e521n65fpj809whmjdr1s1sdb  unique (email)
alter table Profile add constraint UK_1wpe1j4lyc9m4yny8kjfv7y0s  unique (username)
alter table Story add constraint UK_h2d47v2ijwllh2xxgo02hg1r5  unique (url)
alter table Comment add constraint FK_p7g893tkrclgubj06gb0owgtg foreign key (story_id) references Story (id)
alter table Tags add constraint FK_k19i21qfe12kss0t9q4gxsc5l foreign key (Story_id) references Story (id)
create table hibernate_sequence ( next_val bigint )
insert into hibernate_sequence values ( 1 )
